### PR TITLE
Add basics of web app

### PR DESCRIPTION
**Pull request by nikhilwoodruff**
This adds components for the header and footer, and continues the implementation of the new-style navigation.

### CODE REVIEW

**Comment by nikhilwoodruff** [comment]
Screencast from 02-10-21 17_26_19
@MaxGhenis tried to replicate your sketch, what do you think of this? I think some different colours might be better, but not sure which.

**Comment by MaxGhenis** [comment]
Per our discussion, we'll go with four tabs at the top on both desktop and mobile, below the PolicyEngine in top left and social in top right.

**Comment by nikhilwoodruff** [comment]
> Should this be a draft? I'm seeing UK-specific elements.

This PR contains the PolicyEngine-Client React library, and also an example react app that is essentially what policyengine-uk will be. We could just remove the example, but I think when it's all good to merge into policyengine-uk, the only thing left to do is generalise any small features left in this React library.

**Comment by nikhilwoodruff** [comment]
@MaxGhenis I think this is at a point where we can merge - the client-side code is done (server-side can be developed more but less of an immediate need other than code de-duplication and policyengine-us development). Not sure why the actions aren't running but IIRC the action files need to be present in the main branch so might have to merge without.

**Review by MaxGhenis — APPROVED** [review]

**Comment by MaxGhenis** [comment]
Alright let's do this!

**Pull request merged**
