### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by SylviaDu99**
fixes: issue #276

### CODE REVIEW

**Comment by MaxGhenis** [comment]
Please drop 3.9 support while you're here: https://github.com/PolicyEngine/policyengine-core/issues/244

Edit the initial description to link both issues: https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by SylviaDu99** [comment]
Hello @MaxGhenis, thank you for your comment. I want to make sure that I fully get what you meant since only changing the prerequisites in README.md does not solve issue #244. I believe we will be solving issue #244 when working on my other PR #267.

**Comment by MaxGhenis** [comment]
Please fix #244 here, as #267 will take more time. It should be straightforward.

**Review by MaxGhenis — APPROVED** [review]

**Comment by MaxGhenis** [comment]
Please link and close the two issues. Following the instructions in my previous comment will do this automatically

**Pull request merged**
