### PR TITLE
add .vscode, venv to .gitignore; remove .vscode from repository

### LINKED ISSUE #72: Add venv to .gitignore
Some users may want to make a `venv` (and we may want to suggest this), so ignoring contents will avoid git issues there.

For posterity, steps would be something like
```shell
pyenv shell 3.9.16 
python -m venv venv  
```
cc @ibushong

### LINKED ISSUE #181: Add .vscode to .gitignore and remove .vscode from repository
I'd like to propose removing the `.vscode` directory from our repository. This directory typically contains user-specific settings for Visual Studio Code, which aren't necessary for the project's functionality and can cause confusion or conflicts between contributors and/or users.

### PR DESCRIPTION
**Pull request by SylviaDu99**
## Changes Made

add .vscode, venv to .gitignore file; remove .vscode folder from repository

## Related Issues

Fixes #72 
Fixes #181

### CODE REVIEW

**Comment by anth-volk** [comment]
Thanks for your contribution @SylviaDu99! Would you mind updating the changelog by adding an entry to the `changelog_entry.yaml` file? The other PR currently open can serve as a template for how to do so.

**Comment by MaxGhenis** [comment]
Please also edit the initial description to use the Fixes keyword, as to link the issues

**Comment by anth-volk** [comment]
Don't worry, I'll deal with the merge conflict on this, since I created it with changes in #205 last night.

**Comment by anth-volk** [comment]
Also, I took the liberty of editing your initial comment. It's not obvious, but you have to list each fix on a separate line.

**Review by anth-volk — APPROVED** [review]
Thanks @SylviaDu99! Looks great.

In the future, we recommend forking our repo, like you did, but contributing off of a feature branch, and keeping your fork's `master` up-to-date with ours. More info is available on the README of our app repo at https://www.github.com/PolicyEngine/policyengine-app

**Pull request merged**
